version: "3.7"
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8081:8080
        container_name: jenkins
        volumes:
            - ./jenkins_home:/var/jenkins_home
